name = "wardwright"
version = "0.1.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
act = ">= 0.4.0 and < 1.0.0"
non_empty_list = ">= 2.3.0 and < 3.0.0"
trie_again = ">= 1.1.4 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
